### ISSUE TITLE
When restarting robot code data sources have to be re-associated with graph widgets.

### ISSUE THREAD

**Issue by Kython89** [wpilibsuite/shuffleboard#424] opened 2018-03-01 02:38 UTC
After a while a given graph widget will have several of the same data source but on the most recent will plot.  We essentially have to re-setup all our plots whenever we restart robot code.

**Comment by alexanderswerdlow** [comment] 2019-02-21 03:03
We have this issue. Closing shuffleboard after every robot code restart is possible but very frustrating. After a couple minutes, shuffleboard takes 100% of cpu usage to the point where the driver station cannot function. There should be a way to make data sources with the same name not be duplicated.

**Comment by Starlight220** [comment] 2023-03-28 15:16
Duplicate of #720, and resolved by #774.

**Closed** 2023-03-29 12:58 UTC
