### ISSUE TITLE
MJPG Stream Viewer performance

### ISSUE THREAD

**Issue by bhjelstrom** [wpilibsuite/shuffleboard#353] opened 2018-01-11 08:11 UTC
See shuffleboard, chrome, and smartdashboard connect to the Limelight camera stream here:
https://gfycat.com/CapitalEmbellishedBoutu

Shuffleboard is skipping frames, and frames even appear to be compressed on arrival in the shuffleboard viewer. It is hard to tell that it looks extra compressed in the gif, but the image is clearly different whenever I perform this test.

**Comment by SamCarlberg** [comment] 2018-01-11 17:42
Can you run the shuffleboard jar from the command line with

`java -jar -Djavafx.animation.fullspeed=true Shuffleboard-v1.0.0.jar`

This might be due to JavaFX's default tick rate of 60FPS having issues with getting images at 90FPS.

**Comment by bhjelstrom** [comment] 2018-01-11 18:18
I'll try that soon, but the camera stream from Limelight is actually only 15 fps at the moment. 

Another hint is that the stream looks better as I increase the framerate. What was shown in the gif isn't a maximum framerate.

**Comment by bhjelstrom** [comment] 2018-01-12 09:56
No change with the fullspeed option
![cmdcap](https://user-images.githubusercontent.com/13728935/34869418-ae62756c-f73b-11e7-9474-f1da87f3f81a.png)

**Comment by bhjelstrom** [comment] 2018-01-15 20:50
There isn't a fix for shuffleboard perf yet, but we did fix a Limelight-side issue that prevented the stream from working at all. (https://github.com/wpilibsuite/shuffleboard/issues/352)

**Comment by SamCarlberg** [comment] 2018-01-15 21:20
The only other shuffleboard-side explanation I can think of is that the image data isn't available to the JavaFX thread immediately, which would have been fixed by #345 by making the data property update atomically rather than from the JavaFX thread. @bhjelstrom can you run shuffleboard from the current master branch and see if the performance hit is still present?

**Comment by bhjelstrom** [comment] 2018-01-19 07:06
No change with the latest master...

**Comment by ThadHouse** [comment] 2018-02-06 05:09
I was able to reproduce this completely without shuffleboard using only cscore. So we should move this, along with #352 over to the cscore repo.

**Comment by SamCarlberg** [comment] 2018-02-12 19:27
Fixed by https://github.com/wpilibsuite/cscore/pull/119

**Closed by SamCarlberg** 2018-02-12 19:27 UTC
