### ISSUE TITLE
Dashboard Lockup on Robot Code Restart

### ISSUE THREAD

**Issue by Kython89** [wpilibsuite/shuffleboard#396] opened 2018-02-02 22:00 UTC
Whenever we redeploy code to the RoboRio our dashboard locks up.  Part of the NetworkTables table viewer turns black and a majority of our values turn grey.  The only way to restore a functioning dashboard is to restart the dashboard.  We've attached a log and screenshot of this behavior.

![dashboard](https://user-images.githubusercontent.com/13496307/35756678-c77f2b4c-0831-11e8-8b5c-c32338a2feb8.png)
[shuffleboard.log](https://github.com/wpilibsuite/shuffleboard/files/1690959/shuffleboard.log)

**Comment by GaganBhat** [comment] 2018-02-05 04:09
We have been able to replicate this. The exact same problem happens to us. The problem does not occur on smartDashboard though.

**Comment by SamCarlberg** [comment] 2018-02-05 20:47
Looks like a duplicate of #391. Graph widgets aren't being properly reset

**Closed by SamCarlberg** 2018-02-05 20:47 UTC
Labels: bug, duplicate

**Comment by Kython89** [comment] 2018-02-05 21:28
@SamCarlberg Are you sure this is a duplicate of #391?  Our dashboard locks up and parts of it become unresponsive.  In #391 they state that their's crashes.

**Comment by SamCarlberg** [comment] 2018-02-05 21:30
Different symptoms, but the same cause.
