### ISSUE TITLE
x to close tab on tab title

### ISSUE THREAD

**Issue by Crossle86** [wpilibsuite/shuffleboard#541] opened 2018-11-09 17:47 UTC
Consider removing the x to delete tab from the tab title area. We have seen this get clicked accidentally and if that happens after you have been editing, your edits are lost because you have to exit without saving and reopen config to get the deleted tab back. Deleting tab from pull down menu is far less prone to error.

**Comment by SamCarlberg** [comment] 2018-11-09 21:29
Duplicate of #340

**Closed by SamCarlberg** 2018-11-09 21:29 UTC
Labels: duplicate, feature request, ui
