### ISSUE TITLE
Make widget title bar optional

### ISSUE THREAD

**Issue by andrewda** [wpilibsuite/shuffleboard#400] opened 2018-02-05 16:59 UTC
It would be nice to have the option to disable title bars so that they don't take up unnecessary space. If we've got a lot of information to display, every inch is valuable, so the smaller we can make some widgets the better.

**Comment by AustinShalit** [comment] 2018-05-30 19:54
Duplicate of #42

**Comment by andrewda** [comment] 2018-05-30 23:22
Should have made this more clear in my original issue, but I'm talking about the title bars on widgets here. It would be nice to be able to disable the widget titles on some specific widgets if I want, for example, a long boolean box across the top of the window. Having the option to disable the title bar of that boolean box would reduce the footprint of the widget on the screen and allow for a cleaner UI.

I _believe_ #42 is specifically referring to hiding the larger UI features and titles, not the titles of specific widgets.

**Closed** 2019-10-26 16:54 UTC
Labels: feature request, ui
