### ISSUE TITLE
Widget tabs need scroll bars

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#40] opened 2017-07-19 16:32 UTC
See attached GIF

![ezgif-4-faec228fc1](https://user-images.githubusercontent.com/3799260/28378487-2e9496c8-6c65-11e7-9fb9-25d08d884103.gif)

**Comment by nightpool** [comment] 2017-07-19 16:35
We should always shrink and grow the amount of tiles available based on the size of the window. Scroll bars aren't the solution here.

**Comment by SamCarlberg** [comment] 2017-07-19 16:36
Functionally a duplicate of #7

**Closed by SamCarlberg** 2017-07-19 16:36 UTC
Labels: ui
