### ISSUE TITLE
Turning on 'Auto populate' before saving Source prefix behaves unpredictably

### ISSUE THREAD

**Issue by garrett-davidson** [wpilibsuite/shuffleboard#370] opened 2018-01-18 00:37 UTC
Tab auto-population does not work as expected. After much testing, here are my current findings:

All of this was run with the same C++ robot code. We have one axis camera added to the camera server, the default Live Window setup, and several items of various types being sent via SmartDashboard with various prefixes. The testing was centered around our SmartDashboard values with the "Auton" prefix (e.g. "Auton/lTurn1").

Test 1:
Create a tab.
Open tab preferences.
Set prefix to "SmartDashboard/Auton/".
Switch on Auto populate.
Click close.

Result: Every item in NetworkTable, including all of our camera settings, is displayed with fully qualified names (e.g. "CameraPublisher/Axis Camera/Property/exposure_priority", "SmartDashboard/LeftDriveEncoder/Speed"). However, everything with the "Auton" prefix had the prefix stripped (e.g. "lTurn1").

Test 2:
Create a tab.
Open tab preferences.
Set prefix to "SmartDashboard/Auton" (no trailing /).
Switch on Auto populate.
Click close.

Result: Same as Test 1, but several of the widgets changed order, and the "Auton" prefix values no longer had the prefix stripped (e.g. "SmartDashboard/Auton/lTurn1").

Test 3: *Finally figured out how to make it work correctly*
Create a tab.
Open tab preferences.
Set prefix to "SmartDashboard/Auton" (no trailing /).
**Click close.**
**Open tab preferences.**
Switch on Auto populate.
Click close.

Result: Everything with our "Auton" prefix showed up correctly, with the prefix properly stripped, and nothing else appeared.

**Comment by SamCarlberg** [comment] 2018-01-18 00:41
Duplicate of #354 
Closed by #355 

If you're running shuffleboard from the WPILib Eclipse plugins, the fix will be distributed in the next plugins release. That's currently slated for tomorrow night

**Closed by SamCarlberg** 2018-01-18 00:41 UTC
Labels: bug, duplicate
