### ISSUE TITLE
Boolean Box Changing State Independently of Key

### ISSUE THREAD

**Issue by MoSadie** [wpilibsuite/shuffleboard#433] opened 2018-03-13 23:24 UTC
When I have a Boolean key that starts the same as another Boolean key (For example the keys "Low" and "LowPressure"), the boolean box for the key that is common between both boxes ("Low" for this example) will be triggered by either key. I've attached the log and a gif of this behavior using the OutlineViewer's server feature.

[shuffleboard.log](https://github.com/wpilibsuite/shuffleboard/files/1809007/shuffleboard.log)

![shuffleboard bug](https://user-images.githubusercontent.com/8063390/37374942-aa3bba92-26da-11e8-8da2-7b2706e8062a.gif)

**Comment by SamCarlberg** [comment] 2018-03-13 23:26
Duplicate of #419

**Closed by SamCarlberg** 2018-03-13 23:26 UTC
Labels: bug, duplicate
