### ISSUE TITLE
Toggle switches of booleans move outside of the confined oval

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#81] opened 2017-08-02 00:04 UTC
If you make a toggle switch for a boolean it shows an oval that the little switch moves in. When the switch is on the right side, it moves outside of the oval. The left side state is OK.

**Comment by SamCarlberg** [comment] 2017-08-02 00:05
Duplicate of #28

**Closed by SamCarlberg** 2017-08-02 00:05 UTC
